package com.example.myapp


enum class ConfigKey {
    ON_DEMAND_DOWNLOAD_PACKAGE,
    VALIDATE_ON_ANSWER_CHANGE,
    UNIQUE_ID,
    HTML_TEXT,
    UPLOAD_INCOMPLETE,
    SURVEY_LAYOUT,
    RESPONDENT_VALUE,
    CUSTOM_DATA,
    TRIGGER_TEST_MODE,
    OVERLAY_ENABLED_PROGRAM
}