opt_in_rules:
  - weak_delegate
included:
excluded: 
analyzer_rules:
reporter: "xcode"

# Disabled
disabled_rules:
  - trailing_whitespace
  - opening_brace
  - xctfail_message
  - line_length # We don't need line_legnth error because SwiftFormat will wrap at 180
  - cyclomatic_complexity # NOTE: We want to enable this maybe - Will revisit later

# Rules
force_cast: error
force_try: error
type_body_length:
  - 300
  - 400
function_body_length:
  warning: 100
  error: 150
function_parameter_count:
  warning: 8
  error: 8
file_length:
  warning: 800
  error: 1200
nesting:
  type_level:
    warning: 2
    error: 2
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 40
  excluded:
identifier_name:
  min_length: 1
weak_delegate: error
superfluous_disable_command: error
for_where: error

# Custom Rules
custom_rules:
  forbid_date:
    name: "Forbid Date"
    regex: "\\bDate\\b"
    match_kinds:
      - identifier
      - typeidentifier
    message: "Don't use Date"
    severity: error
